const fs = require('fs');

const sunnahDetails = {
  miswak: {
    what: { ru: 'Очищение полости рта специальной палочкой из корня арак.', en: 'Cleaning the mouth with a special stick from the arak root.', uz: 'Og\'iz bo\'shlig\'ini arak ildizidan tayyorlangan maxsus tayoqcha bilan tozalash.', ky: 'Ооз көңдөйүн арак тамырынан жасалган атайын таякча менен тазалоо.' },
    history: { ru: 'Мисвак был важнейшей практикой в жизни Пророка ﷺ, он использовал его после пробуждения, перед омовением, молитвой и входом в дом.', en: 'Miswak was a crucial practice in the Prophet\'s ﷺ life; he used it upon waking up, before ablution, prayer, and entering the house.', uz: 'Misvok Payg\'ambarimiz ﷺ hayotlarida juda muhim amal bo\'lgan; u zot uyg\'onganda, tahoratdan, namozdan va uyga kirishdan oldin undan foydalanganlar.', ky: 'Мисвак Пайгамбарыбыздын ﷺ жашоосундагы эң маанилүү амал болгон; ал ойгонгондо, даараттан, намаздан жана үйгө кирүүдөн мурун колдонгон.' },
    why: { ru: 'Пророк ﷺ говорил, что это очищение для рта и средство достижения довольства Господа.', en: 'The Prophet ﷺ said it is a purification for the mouth and a means of gaining the pleasure of the Lord.', uz: 'Payg\'ambarimiz ﷺ bu og\'izni tozalash va Parvardigorning roziligiga erishish vositasi ekanligini aytganlar.', ky: 'Пайгамбарыбыз ﷺ бул оозду тазалоо жана Жараткандын ыраазычылыгына жетүү каражаты экенин айткан.' },
    spiritual: { ru: 'Следование Сунне Пророка ﷺ, повышение степени молитвы, очищение души и тела перед стоянием перед Аллахом.', en: 'Following the Sunnah of the Prophet ﷺ, elevating the status of the prayer, purifying the soul and body before standing before Allah.', uz: 'Payg\'ambarimiz ﷺ sunnatlariga ergashish, namoz darajasini ko\'tarish, Alloh huzurida turishdan oldin qalb va tana pokligi.', ky: 'Пайгамбарыбыздын ﷺ сүннөтүнө ээрчүү, намаздын даражасын көтөрүү, Аллахтын алдында туруудан мурун жан жана дене тазалыгы.' },
    health: { ru: 'Укрепляет десны, убивает вредные бактерии в полости рта, устраняет запах изо рта, предотвращает кариес.', en: 'Strengthens gums, kills harmful bacteria in the mouth, eliminates bad breath, and prevents tooth decay.', uz: 'Milklarni mustahkamlaydi, og\'iz bo\'shlig\'idagi zararli bakteriyalarni o\'ldiradi, og\'izdan keladigan hidni ketkazadi, tish kariesini oldini oladi.', ky: 'Тиш эттерин бекемдейт, ооз көңдөйүндөгү зыяндуу бактерияларды өлтүрөт, ооздон чыккан жытты кетирет, тиштин чиришин алдын алат.' },
    hadith: { ru: '«Если бы я не боялся обременить мою общину, то обязательно велел бы прикасаться к мисваку перед каждой молитвой» (Бухари).', en: '«If I had not found it difficult for my followers, I would have ordered them to clean their teeth with Siwak for every prayer» (Bukhari).', uz: '«Agar ummatimga mashaqqat bo\'lishidan qo\'rqmaganimda edi, har namoz oldidan misvok ishlatishga buyurar edim» (Buxoriy).', ky: '«Эгер үммөтүмө кыйынчылык болушунан коркпогонумда, ар бир намаздын алдында мисвак колдонууну буюрмакмын» (Бухари).' }
  },
  morning_dua: {
    what: { ru: 'Мольба, которая произносится сразу после пробуждения ото сна.', en: 'Supplication recited immediately after waking up from sleep.', uz: 'Uyqudan uyg\'ongandan so\'ng darhol o\'qiladigan duo.', ky: 'Уйкудан ойгонгондон кийин дароо окула турган дуба.' },
    history: { ru: 'Это дуа было постоянной практикой посланника Аллаха ﷺ каждый раз, когда он открывал глаза навстречу новому дню.', en: 'This dua was a constant practice of the Messenger of Allah ﷺ every time he opened his eyes to a new day.', uz: 'Bu duo Rosululloh ﷺ har safar yangi kunga ko\'z ochganlarida doimiy amallari bo\'lgan.', ky: 'Бул дуба Аллахтын элчисинин ﷺ ар бир жаңы күнгө көзүн ачкан сайын дайыма жасаган амалы болгон.' },
    why: { ru: 'Сон с точки зрения Ислама подобен \'малой смерти\'. Пробуждение — великая милость Аллаха, требующая благодарности.', en: 'Sleep from an Islamic perspective is akin to a \'minor death\'. Waking up is a great mercy from Allah that requires gratitude.', uz: 'Islom nuqtai nazaridan uyqu \'kichik o\'lim\'ga o\'xshaydi. Uyg\'onish Allohning shukrona talab qiladigan ulug\' ne\'matidir.', ky: 'Ислам көз карашы боюнча уйку \'кичине өлүм\' сыяктуу. Уйкудан ойгонуу — бул шүгүр кылууну талап кылган Аллахтын улуу мээрими.' },
    spiritual: { ru: 'Осознание того, что жизнь и смерть (даже временная) в руках Творца. Это настраивает на духовность с первой секунды дня.', en: 'Recognizing that life and death (even temporary) are in the hands of the Creator. It sets a spiritual tone from the first second of the day.', uz: 'Hayot va o\'lim (hatto vaqtinchalik) Yaratganning qo\'lida ekanligini anglash. Bu kunning ilk soniyasidanoq ruhiy kayfiyat baxsh etadi.', ky: 'Жашоо жана өлүм (ал тургай убактылуу) Жараткандын колунда экенин түшүнүү. Бул күндүн биринчи секундасынан баштап рухий маанайды берет.' },
    hadith: { ru: '«Хвала Аллаху, который оживил нас после того, как умертвил, и к Нему предстоит воскрешение!» (Бухари).', en: '«Praise is to Allah Who gives us life after He has caused us to die and unto Him is the return» (Bukhari).', uz: '«Bizni o\'ldirgandan keyin tiriltirgan va Qayta tirilish Uning O\'zigagina bo\'ladigan Allohga hamdlar bo\'lsin!» (Buxoriy).', ky: '«Бизди өлтүргөндөн кийин тирилткен жана Ага кайра тирилүү болгон Аллахка мактоолор болсун!» (Бухари).' }
  },
  fajr_sunnah: {
    what: { ru: 'Два коротких ирекета сунны-намаза перед обязательным утренним Фаджр-намазом.', en: 'Two short rakaats of sunnah prayer before the obligatory morning Fajr prayer.', uz: 'Bomdod farz namozidan oldin ikki qisqa rakat sunnat namozi.', ky: 'Багымдат парз намазынын алдында эки кыска ирекет сүннөт намазы.' },
    history: { ru: 'Аиша передавала, что Пророк ﷺ ни за какими добровольными молитвами не следил так строго, как за этой.', en: 'Aisha reported that the Prophet ﷺ did not strictly adhere to any voluntary prayers as much as he did to this one.', uz: 'Oisha onamiz Payg\'ambarimiz ﷺ hech qaysi nafl namozga bu namozchalik qattiq rioya qilmaganliklarini rivoyat qilganlar.', ky: 'Аиша энебиз Пайгамбарыбыз ﷺ эч бир нафил намазга бул намаздай катуу көңүл бурбаганын риваят кылган.' },
    why: { ru: 'Молитва Фаджр — тяжестейшее время для пробуждения. Эти два ирекета служат ценнейшей наградой для верующего.', en: 'Fajr prayer is the hardest time to wake up. These two rakaats serve as a highly valuable reward for the believer.', uz: 'Bomdod namozi uyg\'onish uchun eng qiyin vaqtdir. Bu ikki rakat mo\'min uchun nihoyatda qimmatli mukofotdir.', ky: 'Багымдат намазы — ойгонуу үчүн эң оор убакыт. Бул эки ирекет момун үчүн өтө баалуу сыйлык болуп саналат.' },
    spiritual: { ru: 'Эти 2 ракаата лучше этого мира и всего, что есть в нем. Они защищают в этот день от лицемерия.', en: 'These 2 rakaats are better than this world and everything in it. They protect from hypocrisy on this day.', uz: 'Bu ikki rakat dunyo va undagi barcha narsadan yaxshiroqdir. Ular o\'sha kuni munofiqlikdan saqlaydi.', ky: 'Бул 2 ирекет бул дүйнөдөн жана андагы бардык нерселерден жакшыраак. Алар ал күнү мунафыктыктан сактайт.' },
    hadith: { ru: '«Два ракаата Фаджра лучше этого мира и того, что есть в нём» (Муслим, 725).', en: '«The two rakaats of Fajr are better than this world and what it contains» (Muslim, 725).', uz: '«Bomdodning ikki rakat (sunnati) dunyo va undagi narsalardan yaxshiroqdir» (Muslim, 725).', ky: '«Багымдаттын эки ирекети (сүннөтү) бул дүйнөдөн жана андагы нерселерден жакшыраак» (Муслим, 725).' }
  },
  rawatib: {
    what: { ru: 'Добровольные 12 ирекетов в сутки, которые привязаны к обязательным намазам (фардам).', en: 'Voluntary 12 rakaats per day, which are attached to the obligatory (fard) prayers.', uz: 'Farz namozlariga biriktirilgan kunlik 12 rakatli nafl namozlar.', ky: 'Парз намаздарына байланышкан күнүнө 12 ирекет нафил намаздар.' },
    history: { ru: 'Сподвижники замечали строгое постоянство Пророка ﷺ в их совершении: 2 до фаджра, 4 до зухра и 2 после, 2 после магриба, 2 после иша.', en: 'Companions noted the Prophet\'s ﷺ strict consistency in offering them: 2 before fajr, 4 before dhuhr and 2 after, 2 after maghrib, 2 after isha.', uz: 'Sahobalar Payg\'ambarimiz ﷺ ularni qat\'iy davomiylikda ado etganliklarini kuzatganlar: bomdoddan oldin 2, peshindan oldin 4 va keyin 2, shomdan keyin 2, xuftondan keyin 2.', ky: 'Сахабалар Пайгамбарыбыздын ﷺ аларды окууда дайым катуу көңүл бурганын байкашкан: багымдаттан мурун 2, бешимден мурун 4 жана кийин 2, шамдан кийин 2, куптандан кийин 2.' },
    why: { ru: 'Суннан-раватиб исправляют и перекрывают недостатки, совершённые человеком в обязательных молитвах.', en: 'Sunnah rawatib correct and cover up shortcomings made by a person in obligatory prayers.', uz: 'Sunnat-ravotiblar insonning farz namozlarida yo\'l qo\'ygan kamchiliklarini to\'g\'rilaydi va qoplaydi.', ky: 'Сүннөт-раватибдер адамдын парз намаздарында кетирген кемчиликтерин оңдойт жана жабат.' },
    spiritual: { ru: 'Строит дом в Раю. Создает защитный вакуум для самого важного столпа веры — намаза.', en: 'Builds a house in Paradise. Creates a protective vacuum for the most important pillar of faith — prayer.', uz: 'Jannatda uy quradi. Iymonning eng muhim ustuni bo\'lmish namoz uchun himoya yaratadi.', ky: 'Бейиште үй курат. Ыймандын эң маанилүү түркүгү болгон намаз үчүн коргоочу вакуум түзөт.' },
    hadith: { ru: '«Кто совершит 12 ирекетов в день и ночь, тому Аллах построит дом в Раю» (Муслим, 728).', en: '«He who prays twelve rakaats a day and night, Allah will build a house for him in Paradise» (Muslim, 728).', uz: '«Kim kechasi va kunduzi o\'n ikki rakat namoz o\'qisa, Alloh unga jannatda uy quradi» (Muslim, 728).', ky: '«Ким күнү-түнү он эки ирекет намаз окуса, Аллах ага Бейиште үй курат» (Муслим, 728).' }
  },
  mosque: {
    what: { ru: 'Выход из дома в состоянии омовения и пеший поход в мечеть на коллективную молитву.', en: 'Leaving the house in a state of ablution and walking to the mosque for congregational prayer.', uz: 'Tahoratli holda uydan chiqish va jamoat namozi uchun masjidga piyoda borish.', ky: 'Даараттуу абалда үйдөн чыгуу жана жамаат намазы үчүн мечитке жөө баруу.' },
    history: { ru: 'В эпоху посланника Аллаха ﷺ все мусульмане (за исключением больных) всегда собирались в мечети по 5 раз в день.', en: 'During the era of the Messenger of Allah ﷺ, all Muslims (except the sick) always gathered in the mosque 5 times a day.', uz: 'Allohning rasuli ﷺ davrida barcha musulmonlar (kasallardan tashqari) kuniga 5 marta har doim masjidga to\'planishar edi.', ky: 'Аллахтын элчисинин ﷺ доорунда бардык мусулмандар (оорулуулардан башкасы) күнүнө 5 жолу дайыма мечитке чогулушчу.' },
    why: { ru: 'Шаги стирают грехи и возвышают статус верующего в иерархии праведников.', en: 'Footsteps wipe away sins and elevate the status of the believer in the hierarchy of the righteous.', uz: 'Qadamlar gunohlarni o\'chiradi va solihlar iyerarxiyasida mo\'minning maqomini ko\'taradi.', ky: 'Кадамдар күнөөлөрдү өчүрөт жана такыбалардын иерархиясында момундун даражасын көтөрөт.' },
    spiritual: { ru: 'Коллективный намаз в 27 раз превосходит индивидуальный. Пешие шаги в мечеть — одни из тяжелейших наград на чаше весов.', en: 'Congregational prayer is 27 times superior to individual prayer. Walking steps to the mosque are among the heaviest rewards on the scales.', uz: 'Jamoat namozi yakka namozdan 27 marta ustundir. Masjidga piyoda yurish – mezon tarozisidagi eng og\'ir mukofotlardan biridir.', ky: 'Жамаат намазы жеке намаздан 27 эсе жогору. Мечитке жөө баруу — таразадагы эң оор сыйлыктардын бири.' },
    health: { ru: 'Физическая активность не менее 5 раз в день, улучшение кровеносной и кардио системы.', en: 'Physical activity at least 5 times a day, improvement of the circulatory and cardiovascular system.', uz: 'Kuniga kamida 5 marta jismoniy faollik, qon aylanish va yurak-qon tomir tizimini yaxshilash.', ky: 'Күнүнө кеминде 5 жолу физикалык активдүүлүк, кан айлануу жана жүрөк-кан тамыр системасын жакшыртуу.' },
    hadith: { ru: '«Поистине, самая большая награда за молитву ждет того, кому пришлось идти дальше всех» (Муслим).', en: '«Indeed, the greatest reward for prayer awaits the one who had to walk the farthest» (Muslim).', uz: '«Darhaqiqat, namoz uchun eng katta mukofot eng uzoq masofaga yurib kelganga nasib etadi» (Muslim).', ky: '«Чындыгында, намаз үчүн эң чоң сыйлык эң алыска баскан адамды күтөт» (Муслим).' }
  },
  post_prayer_dhikr: {
    what: { ru: 'Специальные слова поминания Аллаха, произносимые сразу после обязательного (фард) намаза.', en: 'Special words of remembrance of Allah, recited immediately after the obligatory (fard) prayer.', uz: 'Farz namozidan keyin darhol aytiladigan Allohni zikr qilishning maxsus so\'zlari.', ky: 'Парз намаздан кийин дароо айтылуучу Аллахты зикир кылуунун атайын сөздөрү.' },
    history: { ru: 'Пророк ﷺ обучил этому зикру бедняков Медины, чтобы те смогли опередить богатых мусульман по награде.', en: 'The Prophet ﷺ taught this dhikr to the poor of Madinah so that they could outpace the wealthy Muslims in reward.', uz: 'Payg\'ambarimiz ﷺ bu zikrni Madinaning kambag\'allariga boy musulmonlarni ajrda ortda qoldirishlari uchun o\'rgatganlar.', ky: 'Пайгамбарыбыз ﷺ бул зикирди Мадинанын кедейлерине бай мусулмандардан сооп жагынан озуп кетүүсү үчүн үйрөткөн.' },
    why: { ru: 'Для очищения грехов даже если они подобны пене морской, закрепления завершения молитвы с правильным умонастроением.', en: 'To cleanse sins even if they are like the foam of the sea, to secure the completion of prayer with the right mindset.', uz: 'Gunohlarni, hatto dengiz ko\'pigidek ko\'p bo\'lsa ham, yuvish, namozning tugashini tog\'ri ruhiy kayfiyat bilan mustahkamlash uchun.', ky: 'Күнөөлөрдү, деңиздин көбүкүндөй болсо да, жууш үчүн, намаздын аякташын туура рухий маанай менен бекемдөө үчүн.' },
    spiritual: { ru: 'Заполняет чашу деяний светом. Дарит спокойствие и чувство безопасности до следующего намаза.', en: 'Fills the scale of deeds with light. Brings peace and a sense of security until the next prayer.', uz: 'Amallar tarozisini nur bilan to\'ldiradi. Keyingi namozgacha xotirjamlik va xavfsizlik hissini baxsh etadi.', ky: 'Амалдар таразасын нур менен толтурат. Кийинки намазга чейин тынчтык жана коопсуздук сезимин тартуулайт.' },
    health: { ru: 'Психологическая выгрузка, стабилизация дыхания и пульса после движений в молитве.', en: 'Psychological unloading, stabilization of breathing and pulse after movements in prayer.', uz: 'Ruhiy yengillik, namozdagi harakatlardan so\'ng nafas olish va nabzni barqarorlashtirish.', ky: 'Психологиялык жеңилдөө, намаздагы кыймылдардан кийин дем алууну жана пульсту турукташтыруу.' },
    hadith: { ru: '«Тот, кто после каждой молитвы произносит [этот зикр], простятся его грехи, даже если их как пены морской» (Муслим).', en: '«Whoever recites [this dhikr] after every prayer, his sins will be forgiven, even if they are as abundant as the foam of the sea» (Muslim).', uz: '«Kim har namozdan keyin [bu zikrni] aytsa, uning gunohlari dengiz ko\'pigidek bo\'lsa ham kechiriladi» (Muslim).', ky: '«Ким ар бир намаздан кийин [бул зикирди] айтса, анын күнөөлөрү деңиздин көбүкүндөй болсо да кечирилет» (Муслим).' }
  },
  wudu_sleep: {
    what: { ru: 'Совершение малого омовения (вуду) непосредственно перед тем, как лечь спать.', en: 'Performing minor ablution (wudu) just before going to bed.', uz: 'Yotishdan oldin bevosita kichik tahorat (vudu) olish.', ky: 'Жатаардын алдында дароо кичине даарат (вуду) алуу.' },
    history: { ru: 'Сподвижникам было заповедано поддерживать состояние ритуальной безупречной чистоты, особенно перед сном.', en: 'Companions were commanded to maintain a state of perfect ritual purity, especially before sleep.', uz: 'Sahobalarga, ayniqsa uxlashdan oldin, benuqson tozalik holatini saqlab qolish buyurilgan.', ky: 'Сахабаларга, өзгөчө уктаар алдында, кынтыксыз тазалык абалын сактоо буйрулган.' },
    why: { ru: 'Защита от зла. За того, кто уснул с омовением, ангел делает за него дуа всю ночь.', en: 'Protection from evil. For the one who sleeps with ablution, an angel makes dua for him all night.', uz: 'Yomonlikdan himoya. Tahorat bilan uxlab yotgan kishi uchun farishta tun bo\'yi u uchun duo qiladi.', ky: 'Жамандыктан коргоо. Даарат менен уктаган адам үчүн периште түн бою ал үчүн дуба кылат.' },
    spiritual: { ru: 'Если человек умрет во сне (сон — малая смерть), он умрет на врождённой вере (фитре) и в состоянии чистоты.', en: 'If a person dies in their sleep (sleep is a minor death), they die upon their innate faith (fitrah) and in a state of purity.', uz: 'Agar inson uyqusida vafot etsa (uyqu — bu kichik o\'lim), u tug\'ma iymonida (fitrada) va pok holatda vafot etadi.', ky: 'Эгер адам уйкусунда каза болсо (уйку — бул кичине өлүм), ал тубаса ыйманында (фитра) жана таза абалда өлөт.' },
    health: { ru: 'Доказанное расслабление: вода снимает физическую утомляемость и стресс от прошедшего дня.', en: 'Proven relaxation: water relieves physical fatigue and stress from the past day.', uz: 'Isbotlangan yengillik: suv jismoniy charchoqni va o\'tgan kunning stressini yengillashtiradi.', ky: 'Далилденген эс алуу: суу физикалык чарчоону жана өткөн күндүн стрессин жеңилдетет.' },
    hadith: { ru: '«Если ты отправился ко сну, соверши омовение подобно омовению для намаза...» (Аль-Бухари).', en: '«Whenever you intend to go to bed, perform ablution like that for the prayer...» (Al-Bukhari).', uz: '«Qachon uyquga yotmoqchi bo\'lsang, namozga tahorat olgandek tahorat ol...» (Al-Buxoriy).', ky: '«Качан уктоого жатмакчы болсоң, намазга даарат алгандай даарат ал...» (Аль-Бухари).' }
  },
  ayat_kursi: {
    what: { ru: 'Прочтение величайшего аята Корана (Аль-Бакара, 255-й аят) при подготовке ко сну.', en: 'Recitation of the greatest verse of the Quran (Al-Baqarah, verse 255) when preparing for sleep.', uz: 'Uxlashga hozirlik ko\'rayotganda Qur\'onning eng buyuk oyatini (Baqara surasi, 255-oyat) qiroat qilish.', ky: 'Уктоого даярданып жатканда Курандын эң улуу аятын (Бакара сүрөсү, 255-аят) окуу.' },
    history: { ru: 'Однажды сам Шайтан, пойманный Абу Хурайрой, обучил его этому правилу в надежде спастись, и Пророк ﷺ подтвердил это.', en: 'Once Satan himself, caught by Abu Huraira, taught him this rule in the hope of being saved, and the Prophet ﷺ confirmed this.', uz: 'Bir marta Abu Hurayra tomonidan tutilib qolgan Shaytonning o\'zi qutulib qolish umidida bu qoidani unga o\'rgatgan va Payg\'ambarimiz ﷺ buni tasdiqlaganlar.', ky: 'Бир жолу Абу Хурайра кармап алган Шайтандын өзү кутулуу үмүтү менен ага бул эрежени үйрөткөн жана Пайгамбарыбыз ﷺ муну тастыктаган.' },
    why: { ru: 'Беспроигрышная защита от любого вида шайтанов и джиннов на всю предстоящую ночь.', en: 'Infallible protection from any kind of satans and jinns for the whole upcoming night.', uz: 'Butun tun davomida har xil shaytonlar va jinlardan kafolatli himoya.', ky: 'Түн бою ар кандай шайтандардан жана жиндерден кепилденген коргоо.' },
    spiritual: { ru: 'Верующий получает сильного ангела-охранника от Господа миров. Дарит истинный покой и упование.', en: 'The believer receives a strong guardian angel from the Lord of the worlds. Grants true peace and reliance.', uz: 'Mo\'min olamlar Parvardigoridan kuchli farishta-qo\'riqchiga ega bo\'ladi. Chinakam xotirjamlik va tavakkalni baxsh etadi.', ky: 'Момун ааламдардын Раббисинен күчтүү периште-сакчыга ээ болот. Чыныгы тынчтыкты жана тобокелди тартуулайт.' },
    health: { ru: 'Избавляет от ночных кошмаров, панических настроений и бессонницы.', en: 'Relieves nightmares, panic moods, and insomnia.', uz: 'Tungi dahshatlardan, vahimali kayfiyatlardan va uyqusizlikdan xalos qiladi.', ky: 'Түнкү коркунучтардан, паникалык маанайдан жана уйкусуздуктан арылтат.' },
    hadith: { ru: '«С тобой будет ангел-хранитель от Аллаха, и сатана не сможет приблизиться к тебе до самого утра» (Аль-Бухари).', en: '«There will remain with you a guardian from Allah, and Satan will not approach you until morning» (Al-Bukhari).', uz: '«Sen bilan Alloh tomonidan bir farishta-qo\'riqchi bo\'ladi va shayton senga tonggacha yaqinlasha olmaydi» (Al-Buxoriy).', ky: '«Сени менен Аллах тарабынан бир периште-сакчы болот жана шайтан сага таңга чейин жакындай албайт» (Аль-Бухари).' }
  },
  right_side: {
    what: { ru: 'Положение тела для сна — на правом боку, подложив правую ладонь под щеку.', en: 'Sleeping position — on the right side, placing the right palm under the cheek.', uz: 'Uxlash uchun tana holati - o\'ng tomonda, o\'ng kaftni yonoq ostiga qo\'yib.', ky: 'Уктоо үчүн дененин абалы - оң жамбашта, оң алаканды жаактын астына коюу менен.' },
    history: { ru: 'Абсолютная постоянная и непрерываемая привычка благородного посланника Аллаха ﷺ.', en: 'An absolute constant and uninterrupted habit of the noble Messenger of Allah ﷺ.', uz: 'Olijanob Allohning elchisi ﷺ ning mutlaqdoimiy va uzluksiz odati.', ky: 'Сүйүктүү Аллахтын элчисинин ﷺ абсолюттук туруктуу жана үзгүлтүксүз адаты.' },
    why: { ru: 'Уважение к правой стороне, защита органов и лучшая физиология для сна.', en: 'Respect for the right side, protection of organs, and better physiology for sleep.', uz: 'O\'ng tomonga hurmat, organlarni himoya qilish va uxlash uchun eng yaxshi fiziologiya.', ky: 'Оң тарапты урматтоо, органдарды коргоо жана уктоо үчүн эң жакшы физиология.' },
    spiritual: { ru: 'Это проявление сунны физиологически. Формирует дисциплину даже тогда, когда человек спит.', en: 'It is a physiological manifestation of Sunnah. Forms discipline even when a person is sleeping.', uz: 'Bu sunnatning fiziologik ko\'rinishidir. Inson uxlayotganida ham intizomni shakllantiradi.', ky: 'Бул сүннөттүн физиологиялык көрүнүшү. Адам уктап жатканда да тартипти калыптандырат.' },
    health: { ru: 'Медицински доказано, что сон на левом сдавливает сердце. На правом — желудок освобождается, сердце и легкие функционируют идеально.', en: 'Medically proven that sleeping on the left side compresses the heart. On the right — the stomach is freed, the heart and lungs function perfectly.', uz: 'Chap tomonda uxlash yurakni qisishi tibbiy isbotlangan. O\'ng filialda - oshqozon bo\'shatiladi, yurak va o\'pkalar mukammal ishlaydi.', ky: 'Сол жамбашта уктоо жүрөктү кысары медициналык жактан далилденген. Оң жамбашта - ашказан бошойт, жүрөк жана өпкөлөр кемчиликсиз иштейт.' },
    hadith: { ru: '«Затем ложись на правый бок и произнеси...» (Аль-Бухари, Муслим).', en: '«Then lay down on your right side and say...» (Al-Bukhari, Muslim).', uz: '«Shundan so\'ng o\'ng tomonboshlab yotgin va ayt...» (Al-Buxoriy, Muslim).', ky: '«Андан кийин оң жамбаштап жат да, айт...» (Аль-Бухари, Муслим).' }
  },
  smile: {
    what: { ru: 'Искренняя улыбка людям на улице и домашним, независимо от внешних обстоятельств.', en: 'Sincere smile to people on the street and household members, regardless of external circumstances.', uz: 'Tashqi holatlardan qat\'i nazar, ko\'chadagi odamlarga va uy a\'zolariga samimiy tabassum.', ky: 'Сырткы жагдайларга карабастан, көчөдөгү адамдарга жана үй-бүлө мүчөлөрүнө чын жүрөктөн жылмаюу.' },
    history: { ru: 'Сподвижники признаются, что они никогда не видели никого, кто улыбался бы больше, чем Мухаммад ﷺ.', en: 'Companions confess that they have never seen anyone who smiled more than Muhammad ﷺ.', uz: 'Sahobalar hech qachon Muhammad ﷺ dan ko\'proq tabassum qiladigan kishini ko\'rmaganlarini tan olishadi.', ky: 'Сахабалар Мухаммаддан ﷺ көбүрөөк жылмайган адамды эч качан көрбөгөнүн мойнуна алышат.' },
    why: { ru: 'Улыбка стирает враждебность, снимает агрессию у собеседника, объединяет сердца между верующими разных племен.', en: 'A smile erases hostility, relieves the interlocutor\'s aggression, unifies hearts between believers of different tribes.', uz: 'Tabassum dushmanlikni yo\'q qiladi, suhbatdoshning tajovuzkorligini yo\'qotadi, turli qabilalardagi mo\'minlarning qalblarini birlashtiradi.', ky: 'Жылмаюу душмандыкты жок кылат, маектешинин агрессиясын кетирет, ар кандай уруулардагы момундардын жүрөктөрүн бириктирет.' },
    spiritual: { ru: 'Улыбнуться брату — это милостыня (садака). Она записывается на весы хороших дел так же, как потраченное имущество!', en: 'Smiling at a brother is charity (sadaqah). It is recorded on the scale of good deeds just like spent wealth!', uz: 'Birodaringizga tabassum qilib boqish - bu sadaqadir. U ham xuddi sarflangan boylik kabi mezon tarozisiga yoziladi!', ky: 'Бир тууганыңа жылмаюу — бул садака. Ал сарпталган байлык сыяктуу эле жакшы иштердин таразасына жазылат!' },
    health: { ru: 'Снижает частоту сердечных сокращений, улучшает настроение, выделяет дофамин и серотонин.', en: 'Lowers heart rate, improves mood, releases dopamine and serotonin.', uz: 'Yurak urish tezligini pasaytiradi, kayfiyatni yaxshilaydi, dofamin va serotonin ajralishini ta\'minlaydi.', ky: 'Жүрөктүн кагышын төмөндөтөт, маанайды жакшыртат, дофамин жана серотонин бөлүп чыгарат.' },
    hadith: { ru: '«Твоя улыбка в лицо твоему брату — это садака (милостыня)!» (Ат-Тирмизи).', en: '«Your smiling in the face of your brother is charity!» (At-Tirmidhi).', uz: '«Sening birodaring yuziga ko\'z tashlagan tabassuming — bu sadaqadir!» (At-Termiziy).', ky: '«Сенин бир тууганыңдын жүзүнө жылмайганың — бул садака!» (Ат-Тирмизи).' }
  },
  patience: {
    what: { ru: 'Терпение (сабр) — стойкость переносить все трудности не жалуясь никому, кроме Аллаха.', en: 'Patience (sabr) — resilience to bear all difficulties without complaining to anyone except Allah.', uz: 'Sabr — barcha qiyinchiliklarga Allohdan boshqa hech kimga shikoyat qilmasdan chidash metinligidir.', ky: 'Сабыр — Аллахтан башка эч кимге даттанбай, бардык кыйынчылыктарды көтөрө билүү.' },
    history: { ru: 'Пророки Всевышнего подвергались самым тяжелым испытаниям в истории, подавая великий пример сабра.', en: 'Prophets of the Almighty were subjected to the most severe tests in history, setting a great example of sabr.', uz: 'Qodir Allohning payg\'ambarlari tarixning eng og\'ir sinovlariga duchor bo\'lib, sabrning buyuk o\'rnagini ko\'rsatganlar.', ky: 'Кудуреттүү Аллахтын пайгамбарлары тарыхтагы эң оор сыноолорго туш болуп, сабырдын улуу үлгүсүн көрсөтүшкөн.' },
    why: { ru: 'Беды очищают верующего. Проявление терпения в самом начале потрясения демонстрирует степень веры (Имана).', en: 'Calamities cleanse the believer. Showing patience at the very beginning of a shock demonstrates the degree of faith (Iman).', uz: 'Balolar mo\'minni tozalaydi. Qiyinchilikning dastlabki daqiqalarida sabr ko\'rsatish imon darajasini namoyish etadi.', ky: 'Кыйынчылыктар момунду тазалайт. Соккунун эң башында сабырды көрсөтүү ыймандын даражасын көрсөтөт.' },
    spiritual: { ru: 'Безграничная награда: \'Воистину, терпеливым их награда воздастся полностью без счета\' (Коран 39:10).', en: 'Limitless reward: \'Indeed, the patient will be given their reward without account\' (Quran 39:10).', uz: 'Cheksiz mukofot: \'Albatta, sabr qiluvchilarga mukofotlari hisobsiz berilur\' (Qur\'on 39:10).', ky: 'Чексиз сыйлык: \'Чындыгында, сабырдууларга сооптору эсепсиз берилет\' (Куран 39:10).' },
    health: { ru: 'Мгновенное принятие негативной реальности предохраняет от нервных срывов, депрессий и инфарктов.', en: 'Immediate acceptance of a negative reality protects from nervous breakdowns, depressions, and heart attacks.', uz: 'Salbiy voqelikni darhol qabul qilish asabiy buzilishlar, ruhiy tushkunlik va yurak xurujlaridan himoya qiladi.', ky: 'Терс чындыкты дароо кабыл алуу нервдик бузулуулардан, депрессиялардан жана инфаркттардан коргойт.' },
    hadith: { ru: '«Настоящее терпение (Сабр) — это терпение в первый момент потрясения» (Аль-Бухари).', en: '«True patience (Sabr) is at the first stroke of a calamity» (Al-Bukhari).', uz: '«Haqiqiy sabr — fojianing birinchi zarbasida qilingan sabrdir» (Al-Buxoriy).', ky: '«Чыныгы сабыр — кайгынын биринчи соккусундагы сабыр» (Аль-Бухари).' }
  },
  kindness: {
    what: { ru: 'Забота, уважение и помощь тем, кто живет с тобой по соседству.', en: 'Care, respect, and help to those who live in your neighborhood.', uz: 'Yoningizda yashaydiganlarga g\'amxo\'rlik qilish, ularni hurmat qilish va yordam berish.', ky: 'Сиз менен коңшулаш жашагандарга кам көрүү, урматтоо জ্ঞжана жардам берүү.' },
    history: { ru: 'В исламском обществе статус соседа приравнивался по важности к дальним родственникам.', en: 'In Islamic society, the status of a neighbor was equivalent in importance to distant relatives.', uz: 'Islom jamiyatida qo\'shnining maqomi muhimligi jihatidan uzoq qarindoshlarga tenglashtirilgan.', ky: 'Ислам коомунда коңшунун макамы маанилүүлүгү боюнча алыскы туугандарга теңештирилген.' },
    why: { ru: 'Аллах строго обязал беречь соседей. Защита их чести, помощь едой и тишиной — долг каждого мусульманина.', en: 'Allah strictly obliged to protect neighbors. Protecting their honor, helping with food and silence is the duty of every Muslim.', uz: 'Alloh qo\'shnilarni asrashni qat\'iy farz qilgan. Ularning sha\'nini himoya qilish, oziq-ovqat va xotirjamlik bilan yordam berish har bir musulmonning burchidir.', ky: 'Аллах коңшуларды коргоону катуу милдеттендирген. Алардын намысын коргоо, тамак-аш жана тынчтык менен жардам берүү ар бир мусулмандын милдети.' },
    spiritual: { ru: 'Тот, чей сосед не находится в безопасности от его зла — не войдет в Рай, согласно хадисам.', en: 'The one whose neighbor is not safe from his evil will not enter Paradise, according to hadiths.', uz: 'Hadislar tasdig\'iga ko\'ra, qo\'shnisi uning yomonligidan omonda bo\'lmagan kishi Jannatga kirmaydi.', ky: 'Хадистерге ылайык, коңшусу анын жамандыгынан аман болбогон адам Бейишке кирбейт.' },
    health: { ru: 'Формирует крепкое, безопасное и психологически здоровое общество-утопию.', en: 'Forms a strong, safe, and psychologically healthy utopian society.', uz: 'Mustahkam, xavfsiz va psixologik jihatdan sog\'lom utopik jamiyatni shakllantiradi.', ky: 'Күчтүү, коопсуз жана психологиялык жактан дени сак утопиялык коомду калыптандырат.' },
    hadith: { ru: '«Джибриль столько раз завещал мне хорошее отношение к соседу, что я подумал, что он его сделает моим наследником» (Аль-Бухари).', en: '«Jibril kept recommending me to treat my neighbor well until I thought he would make him my heir» (Al-Bukhari).', uz: '«Jabroil menga qo\'shniga yaxshilik qilishni shunchalik ko\'p vasiyat qildiki, men uni merosxo\'rim qilib qo\'yadimi deb o\'ylab qoldim» (Al-Buxoriy).', ky: '«Жебирейил мага коңшуга жакшы мамиле кылууну ушунчалык көп осуят кылгандыктан, мен аны менин мураскерим кылат го деп ойлоп калдым» (Аль-Бухари).' }
  }
};

const langs = ['ru', 'en', 'uz', 'ky'];

langs.forEach(lang => {
    let output = {};
    for (const [key, details] of Object.entries(sunnahDetails)) {
        for (const [prop, translations] of Object.entries(details)) {
           output[`sunnah_details.${key}.${prop}`] = translations[lang] || translations['ru'];
        }
    }
    
    const existingFile = fs.readFileSync(`src/shared/i18n/translations/${lang}.json`, 'utf8');
    const existingJson = JSON.parse(existingFile);
    for (const [k, v] of Object.entries(output)) {
        if (v) existingJson[k] = v;
    }
    
    fs.writeFileSync(`src/shared/i18n/translations/${lang}.json`, JSON.stringify(existingJson, null, 2));
    console.log(`Updated ${lang}`);
});

